In [55]:
import pandas as pd
import numpy as np

In [56]:
df = pd.read_csv('emails.csv')
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [57]:
df.shape

(5172, 3002)

In [58]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [59]:
df.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [60]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [61]:
df['Prediction'].unique()

array([0, 1], dtype=int64)

In [62]:
df['Prediction'] = df['Prediction'].replace({0:'Not spam',1:'Spam'})

In [63]:
df = df.drop(columns=['Email No.'])

In [64]:
df.head()

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay  valued  \
0    0   0    1    0    0   0    2    0    0   0  ...         0    0       0   
1    8  13   24    6    6   2  102    1   27  18  ...         0    0       0   
2    0   0    1    0    0   0    8    0    0   4  ...         0    0       0   
3    0   5   22    0    5   1   51    2   10   1  ...         0    0       0   
4    7   6   17    1    5   2   57    0    9   3  ...         0    0       0   

   lay  infrastructure  military  allowing  ff  dry  Prediction  
0    0               0         0         0   0    0    Not spam  
1    0               0         0         0   1    0    Not spam  
2    0               0         0         0   0    0    Not spam  
3    0               0         0         0   0    0    Not spam  
4    0               0         0         0   1    0    Not spam  

[5 rows x 3001 columns]

In [65]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [66]:
x = df.drop(columns=['Prediction'],axis=1)
y = df['Prediction']

In [67]:
y.head()

0    Not spam
1    Not spam
2    Not spam
3    Not spam
4    Not spam
Name: Prediction, dtype: object

In [68]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [69]:
KNN = KNeighborsClassifier
knn = KNN(n_neighbors=7)
knn.fit(X_train,Y_train)
y_pred = knn.predict(X_test)

In [70]:
print(f"Prediction: {y_pred}")

Prediction: ['Not spam' 'Spam' 'Not spam' ... 'Not spam' 'Not spam' 'Not spam']


In [71]:
from sklearn.metrics import confusion_matrix

m = metrics.confusion_matrix(Y_test,y_pred)
print(m)

[[635  84]
 [ 49 267]]


Support vector machine

In [72]:
from sklearn.svm import SVC

In [73]:
model = SVC(C=1)
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix
m1 = metrics.confusion_matrix(Y_test,y_pred)
print(m1)

[[700  19]
 [189 127]]
